import type { Emote, EmoteType } from './types';

/**
 * Front-end-only mock data so we can iterate on the UI without any FiveM
 * round-trip. The structure mirrors what `EmoteMenuNUI.lua` will eventually
 * push via `BUILD_EMOTE_MENUS`.
 */
const SEED: Array<[string, string, EmoteType, string?]> = [
  ['so', 'Top Car', 'Emotes', 'general'],
  ['2head', '2 Man 2 Head', 'SharedEmotes', 'shared'],
  ['2fucku', '2 Man Fuck u', 'SharedEmotes', 'shared'],
  ['adjust', 'Adjust', 'Emotes', 'general'],
  ['adjusttie', 'Adjust Tie', 'Emotes', 'general'],
  ['airguitar', 'Air Guitar', 'Emotes', 'general'],
  ['airsynth', 'Air Synth', 'Emotes', 'general'],
  ['argue', 'Argue', 'Emotes', 'general'],
  ['atease', 'At Ease', 'Emotes', 'general'],
  ['attention', 'Attention', 'Emotes', 'general'],
  ['banhammer', 'Ban Hammer', 'PropEmotes', 'prop'],
  ['barrelroll', 'Barrel Roll', 'Dances', 'dances'],
  ['beast', 'Beast', 'Dances', 'dances'],
  ['beg', 'Beg', 'Emotes', 'general'],
  ['blowkiss', 'Blow Kiss', 'Emotes', 'general'],
  ['bow', 'Bow', 'Emotes', 'general'],
  ['box', 'Boxing', 'Dances', 'dances'],
  ['breakdance', 'Break Dance', 'Dances', 'dances'],
  ['burger', 'Burger', 'PropEmotes', 'prop'],
  ['camera', 'Camera', 'PropEmotes', 'prop'],
  ['celebrate', 'Celebrate', 'Emotes', 'general'],
  ['chair', 'Chair Sit', 'Emotes', 'general'],
  ['cheer', 'Cheer', 'Emotes', 'general'],
  ['cheers', 'Cheers', 'PropEmotes', 'prop'],
  ['clap', 'Clap', 'Emotes', 'general'],
  ['clipboard', 'Clipboard', 'PropEmotes', 'prop'],
  ['cocktail', 'Cocktail', 'PropEmotes', 'prop'],
  ['coffee', 'Coffee', 'PropEmotes', 'prop'],
  ['confused', 'Confused', 'Emotes', 'general'],
  ['cop', 'Cop Direct', 'Emotes', 'general'],
  ['crossarms', 'Cross Arms', 'Emotes', 'general'],
  ['cry', 'Cry', 'Emotes', 'general'],
  ['cuffed', 'Cuffed', 'Emotes', 'general'],
  ['dab', 'Dab', 'Dances', 'dances'],
  ['dance1', 'Dance 1', 'Dances', 'dances'],
  ['dance2', 'Dance 2', 'Dances', 'dances'],
  ['dance3', 'Dance 3', 'Dances', 'dances'],
  ['dance4', 'Dance 4', 'Dances', 'dances'],
  ['dance5', 'Dance 5', 'Dances', 'dances'],
  ['dance6', 'Dance 6', 'Dances', 'dances'],
  ['dog', 'Dog Sit', 'AnimalEmotes', 'animal'],
  ['dogplay', 'Dog Play', 'AnimalEmotes', 'animal'],
  ['drink', 'Drink', 'PropEmotes', 'prop'],
  ['drunk', 'Drunk', 'Walks', 'walks'],
  ['eat', 'Eat', 'PropEmotes', 'prop'],
  ['exhausted', 'Exhausted', 'Emotes', 'general'],
  ['facepalm', 'Facepalm', 'Emotes', 'general'],
  ['fail', 'Fail', 'Emotes', 'general'],
  ['fap', 'Fap', 'Emotes', 'general'],
  ['fight', 'Fight', 'Dances', 'dances'],
  ['finger', 'Finger', 'Emotes', 'general'],
  ['fishing', 'Fishing', 'PropEmotes', 'prop'],
  ['flex', 'Flex', 'Emotes', 'general'],
  ['flexarms', 'Flex Arms', 'Emotes', 'general'],
  ['flip', 'Flip', 'Emotes', 'general'],
  ['flipgun', 'Flip Gun', 'Emotes', 'general'],
  ['fly', 'Fly', 'Walks', 'walks'],
  ['gangsign', 'Gang Sign', 'Emotes', 'general'],
  ['guitar', 'Guitar', 'PropEmotes', 'prop'],
  ['hammer', 'Hammer', 'PropEmotes', 'prop'],
  ['hands', 'Hands Up', 'Emotes', 'general'],
  ['handshake', 'Handshake', 'SharedEmotes', 'shared'],
  ['happy', 'Happy', 'Expressions', 'expressions'],
  ['hard', 'Hardstyle', 'Dances', 'dances'],
  ['hifive', 'Hi Five', 'SharedEmotes', 'shared'],
  ['hug', 'Hug', 'SharedEmotes', 'shared'],
  ['idle', 'Idle', 'Emotes', 'general'],
  ['injured', 'Injured', 'Walks', 'walks'],
  ['jog', 'Jog', 'Walks', 'walks'],
  ['jump', 'Jump', 'Emotes', 'general'],
  ['kiss', 'Kiss', 'SharedEmotes', 'shared'],
  ['kneel', 'Kneel', 'Emotes', 'general'],
  ['lay', 'Lay Down', 'Emotes', 'general'],
  ['lean', 'Lean', 'Emotes', 'general'],
  ['lookout', 'Lookout', 'Emotes', 'general'],
  ['mechanic', 'Mechanic', 'Emotes', 'general'],
  ['medic', 'Medic', 'Emotes', 'general'],
  ['mood1', 'Mood Angry', 'Expressions', 'expressions'],
  ['mood2', 'Mood Sad', 'Expressions', 'expressions'],
  ['music', 'Music', 'PropEmotes', 'prop'],
  ['notebook', 'Notebook', 'PropEmotes', 'prop'],
  ['pee', 'Pee', 'Emotes', 'general'],
  ['phone', 'Phone', 'PropEmotes', 'prop'],
  ['photo', 'Photo', 'PropEmotes', 'prop'],
  ['pizza', 'Pizza', 'PropEmotes', 'prop'],
  ['plank', 'Plank', 'Emotes', 'general'],
  ['point', 'Point', 'Emotes', 'general'],
  ['pose1', 'Pose 1', 'Emotes', 'general'],
  ['pose2', 'Pose 2', 'Emotes', 'general'],
  ['pose3', 'Pose 3', 'Emotes', 'general'],
  ['pour', 'Pour', 'PropEmotes', 'prop'],
  ['pray', 'Pray', 'Emotes', 'general'],
  ['proud', 'Proud', 'Walks', 'walks'],
  ['pushup', 'Push Up', 'Emotes', 'general'],
  ['radio', 'Radio', 'PropEmotes', 'prop'],
  ['relax', 'Relax', 'Emotes', 'general'],
  ['rifle', 'Rifle', 'PropEmotes', 'prop'],
  ['salute', 'Salute', 'Emotes', 'general'],
  ['scared', 'Scared', 'Walks', 'walks'],
  ['shrug', 'Shrug', 'Emotes', 'general'],
  ['sit', 'Sit', 'Emotes', 'general'],
  ['sleep', 'Sleep', 'Emotes', 'general'],
  ['smoke', 'Smoke', 'PropEmotes', 'prop'],
  ['sneak', 'Sneak', 'Walks', 'walks'],
  ['stretch', 'Stretch', 'Emotes', 'general'],
  ['sunbathe', 'Sun Bathe', 'Emotes', 'general'],
  ['surrender', 'Surrender', 'Emotes', 'general'],
  ['thinking', 'Thinking', 'Emotes', 'general'],
  ['tired', 'Tired', 'Expressions', 'expressions'],
  ['type', 'Typing', 'PropEmotes', 'prop'],
  ['umbrella', 'Umbrella', 'PropEmotes', 'prop'],
  ['vomit', 'Vomit', 'Emotes', 'general'],
  ['wait', 'Wait', 'Emotes', 'general'],
  ['walk', 'Walk', 'Walks', 'walks'],
  ['wave', 'Wave', 'Emotes', 'general'],
  ['wink', 'Wink', 'Emotes', 'general'],
  ['workout', 'Workout', 'Emotes', 'general'],
  ['yawn', 'Yawn', 'Emotes', 'general'],
  ['yoga', 'Yoga', 'Emotes', 'general'],
  ['zombie', 'Zombie', 'Walks', 'walks'],
];

const FAVORITED = new Set(['so', 'airguitar']);

export const MOCK_EMOTES: Emote[] = SEED.map(
  ([name, label, emoteType, categoryId]) => ({
    id: `${emoteType}_${name}`,
    name,
    label,
    emoteType,
    categoryId,
    isFavorite: FAVORITED.has(name),
    hasPermission: true,
  }),
);
